# Generated by Django 3.2.3 on 2021-05-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_pet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
