# Generated by Django 3.2.3 on 2021-05-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_pet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photos',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
