# Generated by Django 3.2.3 on 2021-05-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_pet_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photos',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to=''),
        ),
    ]
