# Generated by Django 3.2.3 on 2021-05-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_pet_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photos',
        ),
    ]
