# Generated by Django 3.2.3 on 2021-05-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20210528_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myimages',
            name='name',
        ),
    ]
