# Generated by Django 3.2.3 on 2021-05-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_remove_myimages_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyImages',
        ),
    ]
